parameters: {}
environment: {}
packages:
  - name: book-me
    shared: false
    environment:
      beanstalkd_host: ${BEANSTALKD_HOST}
    parameters: {}
    annotations: {}
    functions:
      - name: book
        binary: false
        main: ""
        runtime: php:8.2
        web: true
        webSecure: false
        parameters: {}
        environment: {}
        annotations: {}
        limits: {}
